robot_scara:
          #Publish all joint states
          joint_state_controller:
            type: joint_state_controller/JointStateController
            publish_rate: 50
          
          #Position Controllers
          segundo_joint_position_controller:
            type: effort_controllers/JointPositionController
            joint: segundo_joint
            pid: {p: 20.0, i: 100.0, d: 70.0}
          tercer_joint_position_controller:
            type: effort_controllers/JointPositionController
            joint: tercer_joint
            pid: {p: 20.0, i: 100.0, d: 70.0}
          cuarto_joint_position_controller:
            type: position_controllers/JointPositionController
            joint: cuarto_joint
            
          